/* Shared runtime state for CampusCompass. */
const state = {
  entrance: "NW",
  entranceNodeId: ENTRANCES.NW.id,
  dest: null,
  activeFloor: 1,
  graph: null,
  route: null,
  recommendation: null,
  mode: "idle",
  map: null,
  canvas: null,
  ctx: null,
  mapProvider: null,
  mapNote: "",
  googleOverlay: null,
  editMode: false,
  editorTool: "move",
  dirtyRoomLayout: false,
  overlaySelected: false,
  overlayResizeHandle: null,
  roomResizeHandle: null,
  corridorResizeHandle: null,
  selectedRoomCode: null,
  selectedCorridorId: null,
  selectedNodeId: null,
  hoverRoomCode: null,
  hoverCorridorId: null,
  hoverNodeId: null,
  draggingRoomCode: null,
  draggingRoomResize: null,
  draggingCorridorId: null,
  draggingCorridorResize: null,
  draggingOverlay: null,
  draggingMap: null,
  dragOffset: null,
  editorMessage: "Layout editing is off.",
  editorTone: "",
  saveInFlight: false,
  roomLayoutSnapshot: "",
  roomLayoutResetData: null,
  mapSurface: null,
  editSurface: null,
  appStarted: false,
  demoMode: true,
  visibleLayers: {
    rooms: true,
    corridors: true,
    entrances: true,
    services: true,
    edges: true,
    zones: true,
  },
};

const MIN_ROOM_DIMENSION = 24;
const MIN_CORRIDOR_DIMENSION = 18;
const DEFAULT_CORRIDOR_THICKNESS = 34;
const DEFAULT_CORRIDOR_SPAN_PADDING = 28;
const DEFAULT_CORRIDOR_BLOCK_SIZE = 42;
